import { Product, Customer, ShopSettings, AppUser, Publisher } from '@/types';

export const initialShopSettings: ShopSettings = {
  shopName: "SR Telecom & Library",
  bengaliShopName: "এস. আর. টেলিকম এন্ড লাইব্রেরি",
  tagline: "সকল শ্রেণীর পাঠ্যবই, গাইড ও উন্নতমানের স্টেশনারি সামগ্রী",
  proprietor: "মো: রোকনুজ্জামান",
  phone: "01712-345678",
  secondaryPhone: "01812-987654",
  address: "মেইন রোড, সোনালী ব্যাংক মোড়, থানা সদর",
  vatRegistrationNo: "BIN-192837465-2026",
  defaultAgentCommission: 30, // 30% dynamic commission for agents
  defaultRetailDiscount: 10,   // 10% smart discount for retail customers
  invoiceFooterMessage: "বই জ্ঞানের আলো ছড়ায় • আমাদের সাথে থাকার জন্য ধন্যবাদ",
  invoicePaperDefault: "thermal_58mm",
  invoicePrefix: "INV",
  invoiceIncludeYear: false,
  invoicePadding: 4,
  expensePrefix: "EXP",
  skuPrefix: "BK",
  themeColor: "#0f766e",
  fingerprintEnabled: false,
};

export const initialProducts: Product[] = [
  // Class 0 / Play / Nursery
  {
    id: "prod-bk-01",
    name: "Panjeree Chotoder Bornomala (Adorsholipi)",
    bengaliName: "পাঞ্জেরী ছোটদের বর্ণমালা ও আদর্শলিপি",
    category: "book",
    barcode: "8941001",
    sku: "PAN-CLS0-ADR",
    publisher: "Panjeree",
    bookClass: "Play / Nursery",
    subject: "Bangla & General",
    editionYear: "2026",
    buyPrice: 65,
    mrp: 120,
    stockQty: 45,
    minStockAlert: 10,
    unit: "Piece",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "prod-bk-02",
    name: "Lecture Children Fun Math & Drawing",
    bengaliName: "লেকচার ছোটদের ছবি আঁকা ও মজার গণিত",
    category: "book",
    barcode: "8941002",
    sku: "LEC-CLS0-MAT",
    publisher: "Lecture",
    bookClass: "Play / Nursery",
    subject: "Drawing & Math",
    editionYear: "2026",
    buyPrice: 80,
    mrp: 150,
    stockQty: 30,
    minStockAlert: 8,
    unit: "Piece",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z"
  },

  // Class 5 / Primary
  {
    id: "prod-bk-03",
    name: "Panjeree Primary Somaponi Guide Class 5",
    bengaliName: "পাঞ্জেরী প্রাথমিক বৃত্তি ও গাইড ৫ম শ্রেণী",
    category: "book",
    barcode: "8941003",
    sku: "PAN-CLS5-ALL",
    publisher: "Panjeree",
    bookClass: "Class 5",
    subject: "All Subjects",
    editionYear: "2026",
    buyPrice: 280,
    mrp: 460,
    stockQty: 25,
    minStockAlert: 5,
    unit: "Piece",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z"
  },

  // Class 8 / JSC
  {
    id: "prod-bk-04",
    name: "Lecture Class 8 Gonit Onushiloni",
    bengaliName: "লেকচার ৮ম শ্রেণি গণিত অনুশীলনী",
    category: "book",
    barcode: "8941004",
    sku: "LEC-CLS8-MTH",
    publisher: "Lecture",
    bookClass: "Class 8",
    subject: "Mathematics",
    editionYear: "2026",
    buyPrice: 220,
    mrp: 380,
    stockQty: 40,
    minStockAlert: 10,
    unit: "Piece",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z"
  },

  // Class 9 & 10 (SSC)
  {
    id: "prod-bk-05",
    name: "Panjeree SSC Higher Mathematics Guide Cls 9-10",
    bengaliName: "পাঞ্জেরী এস.এস.সি উচ্চতর গণিত গাইড (৯ম-১০ম)",
    category: "book",
    barcode: "8941005",
    sku: "PAN-SSC-HMATH",
    publisher: "Panjeree",
    bookClass: "Class 10 (SSC)",
    itemType: "Guide",
    subject: "Higher Mathematics",
    editionYear: "2026",
    buyPrice: 320,
    mrp: 550,
    stockQty: 35,
    minStockAlert: 8,
    unit: "Piece",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "prod-bk-pan-eng",
    name: "Panjeree Communicative English Grammar & Composition 9-10",
    bengaliName: "পাঞ্জেরী ইংলিশ গ্রামার এন্ড কম্পোজিশন (৯ম-১০ম)",
    category: "book",
    barcode: "8941011",
    sku: "PAN-SSC-ENG-GRM",
    publisher: "Panjeree",
    bookClass: "Class 10 (SSC)",
    itemType: "English Grammar",
    subject: "English 2nd",
    editionYear: "2026",
    buyPrice: 270,
    mrp: 450,
    stockQty: 40,
    minStockAlert: 10,
    unit: "Piece",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "prod-bk-pan-ban",
    name: "Panjeree Bangla Byakoron o Nirmiti Class 9-10",
    bengaliName: "পাঞ্জেরী বাংলা ব্যাকরণ ও নির্মিতি (৯ম-১০ম)",
    category: "book",
    barcode: "8941012",
    sku: "PAN-SSC-BAN-GRM",
    publisher: "Panjeree",
    bookClass: "Class 10 (SSC)",
    itemType: "Bangla Grammar",
    subject: "Bangla 2nd",
    editionYear: "2026",
    buyPrice: 240,
    mrp: 400,
    stockQty: 38,
    minStockAlert: 8,
    unit: "Piece",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "prod-bk-06",
    name: "Lecture SSC Physics Test Paper & Guide 2026",
    bengaliName: "লেকচার এস.এস.সি পদার্থবিজ্ঞান টেস্ট পেপার ও গাইড",
    category: "book",
    barcode: "8941006",
    sku: "LEC-SSC-PHY",
    publisher: "Lecture",
    bookClass: "Class 10 (SSC)",
    itemType: "Model Test / Test Paper",
    subject: "Physics",
    editionYear: "2026",
    buyPrice: 300,
    mrp: 520,
    stockQty: 28,
    minStockAlert: 6,
    unit: "Piece",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "prod-bk-07",
    name: "Anupam SSC English 1st & 2nd Paper Model Questions",
    bengaliName: "অনুপম এস.এস.সি ইংলিশ ১ম ও ২য় পত্র মডেল টেস্ট",
    category: "book",
    barcode: "8941007",
    sku: "ANU-SSC-ENG",
    publisher: "Anupam",
    bookClass: "Class 10 (SSC)",
    itemType: "English Grammar",
    subject: "English",
    editionYear: "2026",
    buyPrice: 290,
    mrp: 490,
    stockQty: 22,
    minStockAlert: 5,
    unit: "Piece",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z"
  },

  // HSC Inter 1st Year & 2nd Year
  {
    id: "prod-bk-08",
    name: "Panjeree HSC Chemistry 1st Paper (Sanjit Kumar)",
    bengaliName: "পাঞ্জেরী এইচ.এস.সি রসায়ন ১ম পত্র (সঞ্জিত কুমার গুহ সহায়িকা)",
    category: "book",
    barcode: "8941008",
    sku: "PAN-HSC1-CHEM",
    publisher: "Panjeree",
    bookClass: "HSC 1st Year",
    itemType: "Guide",
    subject: "Chemistry 1st",
    editionYear: "2026",
    buyPrice: 420,
    mrp: 720,
    stockQty: 20,
    minStockAlert: 5,
    unit: "Piece",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "prod-bk-09",
    name: "Lecture HSC Physics 2nd Paper (Shahjahan Tapan)",
    bengaliName: "লেকচার এইচ.এস.সি পদার্থবিজ্ঞান ২য় পত্র সমাধান",
    category: "book",
    barcode: "8941009",
    sku: "LEC-HSC2-PHY",
    publisher: "Lecture",
    bookClass: "HSC 2nd Year",
    itemType: "Made Easy / Solution",
    subject: "Physics 2nd",
    editionYear: "2026",
    buyPrice: 440,
    mrp: 750,
    stockQty: 18,
    minStockAlert: 4,
    unit: "Piece",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "prod-bk-10",
    name: "Jupiter HSC Accounting 1st & 2nd Paper Guide",
    bengaliName: "জুপিটার এইচ.এস.সি হিসাববিজ্ঞান সহায়িকা",
    category: "book",
    barcode: "8941010",
    sku: "JUP-HSC-ACC",
    publisher: "Jupiter",
    bookClass: "HSC 1st Year",
    itemType: "Guide",
    subject: "Accounting",
    editionYear: "2026",
    buyPrice: 380,
    mrp: 650,
    stockQty: 15,
    minStockAlert: 4,
    unit: "Piece",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z"
  },

  // Stationery
  {
    id: "prod-st-01",
    name: "Dosh-Taka Dosh-Resta White Exercise Khata (120 Pgs)",
    bengaliName: "১০-টাকা রস্তা সাদা পেপার খাতা (১২০ পৃষ্ঠা)",
    category: "stationery",
    barcode: "8942001",
    sku: "ST-KHT-120",
    buyPrice: 28,
    mrp: 45,
    stockQty: 120,
    minStockAlert: 20,
    unit: "Piece",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "prod-st-02",
    name: "Practical Laboratory Biology / Physics Khata",
    bengaliName: "ব্যবহারিক ল্যাবরেটরি খাতা (বায়োলজি/ফিজিক্স)",
    category: "stationery",
    barcode: "8942002",
    sku: "ST-PRC-KHT",
    buyPrice: 50,
    mrp: 85,
    stockQty: 50,
    minStockAlert: 10,
    unit: "Piece",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "prod-st-03",
    name: "Matador Pinpoint Ball Pen (Box of 20 Pcs)",
    bengaliName: "ম্যাটাডোর পিনপয়েন্ট বল পেন (২০ পিসের বক্স)",
    category: "stationery",
    barcode: "8942003",
    sku: "ST-MAT-PNP20",
    buyPrice: 85,
    mrp: 120,
    stockQty: 60,
    minStockAlert: 15,
    unit: "Box",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "prod-st-04",
    name: "Matador Pinpoint Ball Pen (Single Pcs)",
    bengaliName: "ম্যাটাডোর পিনপয়েন্ট বল পেন (প্রতি পিস)",
    category: "stationery",
    barcode: "8942004",
    sku: "ST-MAT-PIN-S",
    buyPrice: 4.5,
    mrp: 6,
    stockQty: 400,
    minStockAlert: 50,
    unit: "Piece",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "prod-st-05",
    name: "Nataraj 2B Drawing & Exam Pencil (Pack of 10)",
    bengaliName: "নটরাজ ২বি পেন্সিল প্যাকেট (১০ পিস)",
    category: "stationery",
    barcode: "8942005",
    sku: "ST-NAT-PNC10",
    buyPrice: 55,
    mrp: 90,
    stockQty: 45,
    minStockAlert: 10,
    unit: "Pkt",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "prod-st-06",
    name: "Deli Metal Compass & Geometry Box",
    bengaliName: "দেলি মেটাল জ্যামিতি বক্স",
    category: "stationery",
    barcode: "8942006",
    sku: "ST-DELI-GEO",
    buyPrice: 120,
    mrp: 190,
    stockQty: 25,
    minStockAlert: 5,
    unit: "Piece",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z"
  }
];

export const initialCustomers: Customer[] = [
  {
    id: "cust-agent-01",
    name: "Anowar Book House (Agent)",
    phone: "01711-223344",
    address: "বাজারঘাট মোড়, ইউনিয়ন বাজার",
    type: "agent",
    defaultCommissionRate: 32, // 32% wholesale commission on books
    totalPurchased: 45200,
    totalPaid: 35000,
    currentDue: 10200, // ৳10,200 due
    createdAt: "2026-01-10T10:00:00Z"
  },
  {
    id: "cust-agent-02",
    name: "Sonargaon Academy Sub-Agent",
    phone: "01912-334455",
    address: "স্কুল গেট, সোনারগাঁও হাই স্কুল",
    type: "agent",
    defaultCommissionRate: 28, // 28% wholesale commission
    totalPurchased: 28400,
    totalPaid: 24000,
    currentDue: 4400, // ৳4,400 due
    createdAt: "2026-01-15T11:30:00Z"
  },
  {
    id: "cust-single-01",
    name: "Rafiqul Islam (Retail / Guardian)",
    phone: "01819-887766",
    address: "উত্তর পাড়া, নিজ গ্রাম",
    type: "single",
    defaultCommissionRate: 0,
    totalPurchased: 3600,
    totalPaid: 3100,
    currentDue: 500, // ৳500 due
    createdAt: "2026-02-01T14:20:00Z"
  }
];

export const initialUsers: AppUser[] = [
  {
    id: "usr-admin",
    name: "মো: রোকনুজ্জামান (Admin)",
    username: "admin",
    role: "admin",
    pin: "1234",
  },
  {
    id: "usr-staff",
    name: "বিক্রয়কর্মী (Cashier / Staff)",
    username: "cashier",
    role: "staff",
    pin: "5678",
  },
];

export const initialPublishers: Publisher[] = [
  {
    id: "pub-panjeree",
    name: "Panjeree Publications",
    bengaliName: "পাঞ্জেরী পাবলিকেশন্স",
    code: "PANJEREE",
    phone: "02-9568741",
    address: "বাংলাবাজার, ঢাকা-১১০০",
    logoUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=120&h=120&fit=crop&crop=faces&q=80",
    notes: "Bangladesh leading guide and creative textbook publisher",
    defaultCommissionRate: 35,
    itemCommissions: [
      { itemType: "Guide", commissionRate: 35, notes: "All class guides & sahayika" },
      { itemType: "English Grammar", commissionRate: 40, notes: "Communicative English 6-12" },
      { itemType: "Bangla Grammar", commissionRate: 40, notes: "Byakoron o Nirmiti" },
      { itemType: "Model Test / Test Paper", commissionRate: 32, notes: "SSC & HSC Model Questions" },
    ],
    createdAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "pub-lecture",
    name: "Lecture Publications",
    bengaliName: "লেকচার পাবলিকেশন্স",
    code: "LECTURE",
    phone: "02-9554123",
    address: "বাংলাবাজার, ঢাকা-১১০০",
    logoUrl: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=120&h=120&fit=crop&crop=faces&q=80",
    notes: "Renowned educational guidebooks for primary, secondary and higher secondary",
    defaultCommissionRate: 35,
    itemCommissions: [
      { itemType: "Guide", commissionRate: 35, notes: "Primary & High School Guides" },
      { itemType: "English Grammar", commissionRate: 42, notes: "English 1st & 2nd Grammar" },
      { itemType: "Bangla Grammar", commissionRate: 38, notes: "Bangla 2nd Paper Byakoron" },
      { itemType: "Made Easy / Solution", commissionRate: 34, notes: "HSC Chapterwise Solutions" },
      { itemType: "Model Test / Test Paper", commissionRate: 32, notes: "Board Exam Test Papers" },
    ],
    createdAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "pub-anupam",
    name: "Anupam Prakashani",
    bengaliName: "অনুপম প্রকাশনী",
    code: "ANUPAM",
    phone: "02-7112345",
    address: "৩৮ বাংলাবাজার, ঢাকা",
    logoUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=120&h=120&fit=crop&crop=faces&q=80",
    notes: "English and science model tests & test papers",
    defaultCommissionRate: 38,
    itemCommissions: [
      { itemType: "English Grammar", commissionRate: 45, notes: "High discount English grammar" },
      { itemType: "Bangla Grammar", commissionRate: 40, notes: "Bangla Grammar editions" },
      { itemType: "Guide", commissionRate: 35, notes: "General Subject Guides" },
      { itemType: "Model Test / Test Paper", commissionRate: 35, notes: "Annual Model Tests" },
    ],
    createdAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "pub-jupiter",
    name: "Jupiter Publications",
    bengaliName: "জুপিটার পাবলিকেশন্স",
    code: "JUPITER",
    phone: "02-7168901",
    address: "৩৬ বাংলাবাজার, ঢাকা",
    logoUrl: "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=120&h=120&fit=crop&crop=faces&q=80",
    notes: "Commerce, Arts and Science guides for HSC",
    defaultCommissionRate: 35,
    itemCommissions: [
      { itemType: "Guide", commissionRate: 35, notes: "Commerce & Science Guides" },
      { itemType: "Made Easy / Solution", commissionRate: 36, notes: "Accounting & Finance Solutions" },
      { itemType: "Bangla Grammar", commissionRate: 38, notes: "HSC Bangla Sahitya & Grammar" },
    ],
    createdAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "pub-nctb",
    name: "NCTB (Board)",
    bengaliName: "জাতীয় শিক্ষাক্রম ও পাঠ্যপুস্তক বোর্ড",
    code: "NCTB",
    phone: "02-9565651",
    address: "৬৯-৭০ মতিঝিল বা/এ, ঢাকা",
    logoUrl: "https://images.unsplash.com/photo-1532012164546-f432f2e37b73?w=120&h=120&fit=crop&crop=faces&q=80",
    notes: "Official government board curriculum textbooks",
    defaultCommissionRate: 15,
    itemCommissions: [
      { itemType: "Textbook (Board)", commissionRate: 15, notes: "Standard Board Book commission" },
    ],
    createdAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "pub-nobodut",
    name: "Nobodut Prokashoni",
    bengaliName: "নবদূত প্রকাশনী",
    code: "NOBODUT",
    phone: "02-9587654",
    address: "বাংলাবাজার, ঢাকা",
    logoUrl: "https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=120&h=120&fit=crop&crop=faces&q=80",
    notes: "Secondary and higher secondary exam preparation books",
    defaultCommissionRate: 36,
    itemCommissions: [
      { itemType: "English Grammar", commissionRate: 42, notes: "Nobodut English Grammar series" },
      { itemType: "Bangla Grammar", commissionRate: 40, notes: "Nobodut Bangla 2nd series" },
      { itemType: "Guide", commissionRate: 36, notes: "Exam Guides" },
      { itemType: "Model Test / Test Paper", commissionRate: 35, notes: "Nobodut Test Papers" },
    ],
    createdAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "pub-royal",
    name: "Royal Scientific Publications",
    bengaliName: "রয়্যাল সায়েন্টিফিক",
    code: "ROYAL",
    phone: "02-9561234",
    address: "বাংলাবাজার, ঢাকা",
    logoUrl: "https://images.unsplash.com/photo-1507842229451-7f01be837453?w=120&h=120&fit=crop&crop=faces&q=80",
    notes: "Physics, Chemistry and Higher Math practical laboratory books",
    defaultCommissionRate: 35,
    itemCommissions: [
      { itemType: "Practical Notebook", commissionRate: 40, notes: "Lab & practical notebooks" },
      { itemType: "Guide", commissionRate: 35, notes: "Science practical guides" },
    ],
    createdAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "pub-popy",
    name: "Popy Library",
    bengaliName: "পপি লাইব্রেরি",
    code: "POPY",
    phone: "02-7119876",
    address: "বাংলাবাজার, ঢাকা",
    logoUrl: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=120&h=120&fit=crop&crop=faces&q=80",
    notes: "Dictionaries, general knowledge and children literature",
    defaultCommissionRate: 35,
    itemCommissions: [
      { itemType: "Dictionary", commissionRate: 40, notes: "Bangla & English Dictionaries" },
      { itemType: "General Knowledge", commissionRate: 40, notes: "Current affairs & GK" },
      { itemType: "English Grammar", commissionRate: 38, notes: "Translation & Grammar" },
    ],
    createdAt: "2026-01-01T00:00:00Z"
  }
];


